### ISSUE TITLE
Missing rpm's

### ISSUE THREAD

**Issue by richard-allen** [E-F-A/v5#8]
On a freshly installed efa5 system, deployed from a minimal RHEL 9 install, there are few missing rpm's that should probably be installed.

tuned.   This tool performs valuable tuning for the OS, depending on hardware or virtualization.  Makes things run smoother. 
bash-completion and vim-enhanced.  Just because :-)

**Comment by pdwalker** [comment]
seconded for vim-enhanced because we know all other editors are not actually useful </editor religious war never ends>
